include:
- ./functions/unemployment/getMidYearUnemp.py
kind: ArchiveUploadSpec
name: functions-unemployment-getmidyearunemp-py-fgtC

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getmidyearunemp-2ea5fea3-2928-4ca2-937b-d42e31a2775d
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-unemployment-getmidyearunemp-py-fgtC
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-27T18:18:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getmidyearunemp
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getmidyearunemp-2ea5fea3-2928-4ca2-937b-d42e31a2775d
      namespace: ""
  requestsPerPod: 1
  resources: {}
