include:
- ./functions/tweet/getDailyTweets.py
kind: ArchiveUploadSpec
name: functions-tweet-getdailytweets-py-Oe1Y

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getdailytweets-b6e81410-c1de-4826-be6f-93a15bf82892
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-tweet-getdailytweets-py-Oe1Y
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-27T13:46:17Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getdailytweets
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getdailytweets-b6e81410-c1de-4826-be6f-93a15bf82892
      namespace: ""
  requestsPerPod: 1
  resources: {}
