include:
- ./functions/unemployment/getUnemployment.py
kind: ArchiveUploadSpec
name: functions-unemployment-getunemployment-py-dmnA

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getunemployment-337de2fc-8699-4fbc-b2ba-e9194d7dba8c
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-unemployment-getunemployment-py-dmnA
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-22T00:05:23Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getunemployment
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getunemployment-337de2fc-8699-4fbc-b2ba-e9194d7dba8c
      namespace: ""
  requestsPerPod: 1
  resources: {}
