apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: addaffords
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: addAffords.main
    packageref:
      name: addaffords
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
include:
- ./functions/affords/addAffords.py
kind: ArchiveUploadSpec
name: functions-affords-addaffords-py-lgXi

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addaffords-8acd1c9b-d931-4c73-adeb-8a3069073bf7
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-affords-addaffords-py-lgXi
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T11:47:07Z"
