include:
- ./functions/airmonitor/airmonitor.py
kind: ArchiveUploadSpec
name: functions-airmonitor-airmonitor-py-gRxy

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestair-01da1d60-f51e-42ff-aebf-56ff9c1e73cf
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-airmonitor-airmonitor-py-gRxy
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T17:12:19Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: harvestair
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: air-const
    namespace: ""
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: harvestair-01da1d60-f51e-42ff-aebf-56ff9c1e73cf
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
include:
- ./functions/airmonitor/airmonitor.py
kind: ArchiveUploadSpec
name: functions-airmonitor-airmonitor-py-cAOB

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestair-b1becdcc-7b13-496d-9a7f-3d7a25e237e8
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-airmonitor-airmonitor-py-cAOB
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T22:47:52Z"

---
include:
- ./functions/airmonitor/airmonitor.py
kind: ArchiveUploadSpec
name: functions-airmonitor-airmonitor-py-7AZe

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestair-ffbc74fd-4d2b-49a7-a52b-448edbebae46
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-airmonitor-airmonitor-py-7AZe
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T22:49:02Z"

---
include:
- ./functions/tweet/getTweets.py
kind: ArchiveUploadSpec
name: functions-tweet-gettweets-py-tv7l

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestair-b667df3a-5bc7-4f64-9d32-b3faa9b0d373
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-tweet-gettweets-py-tv7l
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-22T00:43:39Z"
