include:
- ./functions/tweet/getTweetsByState.py
kind: ArchiveUploadSpec
name: functions-tweet-gettweetsbystate-py-qx0a

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: gettweetsbystate-138a3cb6-f1b0-4bf9-88ee-cdefa0eb9ea1
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-tweet-gettweetsbystate-py-qx0a
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-27T16:31:47Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: gettweetsbystate
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: gettweetsbystate-138a3cb6-f1b0-4bf9-88ee-cdefa0eb9ea1
      namespace: ""
  requestsPerPod: 1
  resources: {}
