include:
- ./functions/unemployment/IndexUnemployment.py
kind: ArchiveUploadSpec
name: functions-unemployment-indexunemployment-py-u8Ss

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addunemployment-59769618-4c17-4382-8565-5b3490226a78
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-unemployment-indexunemployment-py-u8Ss
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T15:59:09Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: addunemployment
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: addunemployment-59769618-4c17-4382-8565-5b3490226a78
      namespace: ""
  requestsPerPod: 1
  resources: {}
