include:
- ./functions/airmonitor/airmonitor.py
kind: ArchiveUploadSpec
name: functions-airmonitor-airmonitor-py-gRxy

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestair-01da1d60-f51e-42ff-aebf-56ff9c1e73cf
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-airmonitor-airmonitor-py-gRxy
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T17:12:19Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: harvestair
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: air-const
    namespace: ""
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: harvestair-01da1d60-f51e-42ff-aebf-56ff9c1e73cf
      namespace: ""
  requestsPerPod: 1
  resources: {}
