include:
- ./functions/asx/getQuarterlyASX.py
kind: ArchiveUploadSpec
name: functions-asx-getquarterlyasx-py-YCVc

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getquarterlyasx-e699d575-6738-4942-abac-5914e30c5ea7
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-asx-getquarterlyasx-py-YCVc
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-28T13:59:57Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getquarterlyasx
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getquarterlyasx-e699d575-6738-4942-abac-5914e30c5ea7
      namespace: ""
  requestsPerPod: 1
  resources: {}
