include:
- ./functions/unemployment/getQuarterlyUnemployment.py
kind: ArchiveUploadSpec
name: functions-unemployment-getquarterlyunemployment-py-T4g2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getquarterlyunemp-56fab8b4-75bf-441e-a7e4-4d4ca16dc7ae
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-unemployment-getquarterlyunemployment-py-T4g2
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-28T14:52:32Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getquarterlyunemp
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getquarterlyunemp-56fab8b4-75bf-441e-a7e4-4d4ca16dc7ae
      namespace: ""
  requestsPerPod: 1
  resources: {}
