include:
- ./functions/affords/addAffords.py
kind: ArchiveUploadSpec
name: functions-affords-addaffords-py-dTC3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addafford-92a1cc0f-53a0-4be1-8fc2-cc15a1e03515
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-affords-addaffords-py-dTC3
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T11:47:20Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: addafford
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39x
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: addafford-92a1cc0f-53a0-4be1-8fc2-cc15a1e03515
      namespace: ""
  requestsPerPod: 1
  resources: {}
