apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: addasx
spec:
  createingress: false
  functionref:
    functionweights: null
    name: addasx
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /asx/{id}
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /asx/{id}
