apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getdailyasx
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getdailyasx
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /asx/daily
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /asx/daily
