apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: gettweetsbystate
spec:
  createingress: false
  functionref:
    functionweights: null
    name: gettweetsbystate
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /tweets/state
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /tweets/state
