apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: addair
spec:
  createingress: false
  functionref:
    functionweights: null
    name: addair
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /air
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /air
