apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: gettweets
spec:
  createingress: false
  functionref:
    functionweights: null
    name: gettweets
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /tweets
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /tweets
