apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getunemployment
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getunemployment
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /unemployment
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /unemployment
