apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: harvestair
spec:
  createingress: false
  functionref:
    functionweights: null
    name: harvestair
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /harvestair
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /harvestair
